server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8081/
          Predicates:
            - Path=/demo1/**
        - id: Microservice2
          uri: http://localhost:8080/
          Predicates:
            - Path=/demo2/**