
server:
  port: 8500

spring:
  application:
    name: ApplicationGateway-practice
  profiles:
    active: default
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: LIBRARYSERVICE
          uri: lb://LIBRARYSERVICE
          predicates:
            - Path=/library/**
        - id: BOOKSERVICE
          uri: lb://BOOKSERVICE
          predicates:
            - Path=/book/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 0.1

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
