server:
  port: 8085
spring:
  application:
    name: Application-Gateway
  cloud:
    gateway:
      routes:
        - id: Demostration-service
          uri: http://localhost:9090
          Predicates:
            - Path=/demo/**